name: Build Kivy APK

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Test internet connection
      run: ping -c 3 google.com

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk \
          libncurses6 libffi-dev libssl-dev libsqlite3-dev libjpeg-dev libfreetype6-dev \
          libsdl2-dev libgles2-mesa-dev libgstreamer1.0-dev libmtdev-dev libgl1-mesa-dev \
          libavcodec-dev libavformat-dev libswscale-dev libbz2-dev liblzma-dev zlib1g-dev \
          libtiff-dev libx11-dev libpng-dev libsm6 libxext6 libxrender-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install --no-cache-dir buildozer cython
        buildozer init || true

    - name: Install Android SDK components
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "build-tools;31.0.0" \
          "platforms;android-31"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-apk
        path: bin/*.apk
